[package]
name = "digestify"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
typst-wasm-protocol = "0.0.2"
digest = "0.10.7"
md4 = "0.10.2"
md5 = "0.8.0"
sha1 = "0.10.6"
sha2 = "0.10.9"
